create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text not null,
  title text not null,
  url text not null,
  address text,
  district text,
  rent integer,
  area_ping numeric,
  first_floor_ping numeric,
  score_total integer not null default 0,
  score_breakdown jsonb not null default '{}'::jsonb,
  enrichment jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  status text not null default 'new',
  notified_high_score boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  notes text,
  unique(source, source_id)
);
create index if not exists listings_score_idx on public.listings(score_total desc);
create index if not exists listings_last_seen_idx on public.listings(last_seen_at desc);
