-- Safe to rerun; automatic scans never write manual_review or review_version.
alter table public.listings add column if not exists manual_review jsonb;
alter table public.listings add column if not exists review_version integer not null default 0;

create table if not exists public.listing_history (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id),
  observed_at timestamptz not null default now(),
  rent integer,
  area_ping numeric,
  first_floor_ping numeric,
  is_active boolean
);
create index if not exists listing_history_listing_idx on public.listing_history(listing_id, observed_at desc);
create or replace function public.record_listing_history() returns trigger
language plpgsql set search_path = public as $$
begin
  if TG_OP = 'INSERT' then
    insert into public.listing_history(listing_id,rent,area_ping,first_floor_ping,is_active)
      values(new.id,new.rent,new.area_ping,new.first_floor_ping,new.is_active);
  elsif row(new.rent,new.area_ping,new.first_floor_ping,new.is_active) is distinct from row(old.rent,old.area_ping,old.first_floor_ping,old.is_active) then
    insert into public.listing_history(listing_id,rent,area_ping,first_floor_ping,is_active)
      values(new.id,new.rent,new.area_ping,new.first_floor_ping,new.is_active);
  end if;
  return new;
end;
$$;
drop trigger if exists listing_history_trigger on public.listings;
create trigger listing_history_trigger after insert or update on public.listings for each row execute function public.record_listing_history();

create table if not exists public.scan_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null,
  scanned integer not null default 0,
  error text
);
-- All access uses the authenticated application server; no anonymous client policies.
alter table public.listings enable row level security;
alter table public.listing_history enable row level security;
alter table public.scan_runs enable row level security;
